//@ sourceMappingURL=tests.map
// Generated by CoffeeScript 1.6.1
(function() {

  module('Тестирование модели');

  test('Класс Player', function() {
    var a, b, c;
    a = new Player();
    ok((a.name != null) && (a.x != null) && (a.y != null), 'конструктор из случайных значений');
    b = new Player(a);
    ok((b.name != null) && b.name === a.name && (b.x != null) && b.x === a.x && (b.y != null) && b.y === a.y, 'копирующий конструктор');
    c = new Player('test', 10, -15);
    ok(c.name === 'test' && c.x === 10 && c.y === -15, 'конструктор по значениям');
    equal(c.html(), "<div id='test' class='player'>test</div>", 'HTML представление');
    deepEqual(c.raw(), {
      name: 'test',
      x: 10,
      y: -15
    }, 'получение сырого объекта');
    c.change({
      x: 100,
      y: 1000
    });
    return deepEqual(c.raw(), {
      name: 'test',
      x: 100,
      y: 1000
    }, 'изменение значений объекта');
  });

}).call(this);
